# Generated by Django 4.2.14 on 2024-08-29 05:50

import cabin_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='type',
            field=models.CharField(max_length=50, null=True, validators=[cabin_booking.models.Validate_cabin_type]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
