# Generated by Django 5.1 on 2024-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_reset',
            field=models.BooleanField(default=True),
        ),
    ]
