# Generated by Django 5.1 on 2024-09-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_booking', '0002_user_is_password_reset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('start_date_time', 'end_date_time')},
        ),
    ]
