# Generated by Django 4.2.14 on 2024-08-29 05:51

import cabin_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_booking', '0002_alter_cabin_type_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[cabin_booking.models.Validate_cabin_type]),
        ),
    ]
