# Generated by Django 5.1 on 2024-09-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_booking', '0003_alter_bookingslot_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together=set(),
        ),
    ]
