# Generated by Django 5.1 on 2024-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_booking', '0004_alter_bookingslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
